export const FHY_HEAVY_RAIN_START_EVENT = 'FHY-HEAVY-RAIN-START-EVENT'
export const FHY_HEAVY_RAIN_START_EVENT_SMS = 'FHY-HEAVY-RAIN-START-EVENT-SMS'
export const FHY_START_RESPONSE_TEAM = 'FHY-START-RESPONSE-TEAM'
export const FHY_HEAVY_RAIN_FAX = 'FHY-HEAVY-RAIN-FAX'
